import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import insight_img from "../../assets/images/Insight_img.png";
import review_one from "../../assets/images/review1.png";
import review_two from "../../assets/images/review2.png";
import "./insight.css";
const Insight = () => {
    return (_jsxs("div", { children: [_jsx("div", { className: "section_one_wrapper", children: _jsxs("section", { className: "section_one", children: [_jsx("div", { children: _jsx("img", { src: insight_img, alt: "insights" }) }), _jsxs("div", { className: "col_2", children: [_jsx("p", { className: "insight_title", children: "Insights and Tips" }), _jsx("p", { className: "insight_desc", children: "Stay informed and optimize your transactions" }), _jsx("button", { className: "insight_button", children: "Read More" })] })] }) }), _jsxs("section", { className: "dt_section", children: [_jsxs("div", { className: "dt_col", children: [_jsx("div", { children: _jsx("img", { src: insight_img, alt: "insights", className: "dt_img" }) }), _jsxs("div", { children: [_jsx("p", { className: "dt_col_title", children: "Transaction Optimization" }), _jsx("p", { className: "insight_desc", children: "Learn how to reduce gas fees" }), _jsx("button", { children: "Gas Optimization" })] })] }), _jsxs("div", { className: "dt_col", children: [_jsx("div", { children: _jsx("img", { src: insight_img, alt: "insights", className: "dt_img" }) }), _jsxs("div", { children: [_jsx("p", { className: "dt_col_title", children: "Real Time updates" }), _jsx("p", { className: "insight_desc", children: "recieve instant notifications" }), _jsx("button", { children: "Notifications" })] })] })] }), _jsx("section", { className: "section_3_wrapper", children: _jsxs("div", { className: "section_3", children: [_jsxs("div", { children: [_jsx("p", { className: "insight_title", children: "User Review" }), _jsx("p", { className: "insight_desc", children: "See what our users are saying" }), _jsx("button", { className: "insight_button", children: "Write a Review" })] }), _jsxs("div", { className: "review_section", children: [_jsx("img", { src: review_one, alt: "user review", className: "review_card" }), _jsx("img", { src: review_two, alt: "user review", className: "review_card" })] })] }) })] }));
};
export default Insight;
